/**
 * First Light onboarding email sequence
 * Triggered when new user signs up
 */

interface User {
  email: string;
  name?: string;
  created_at: string;
}

const RESEND_KEY = process.env.RESEND_KEY_FIRSTLIGHT || '';
const FROM_EMAIL = 'LUMEN <hello@firstlight.to>';

async function sendEmail(to: string, subject: string, html: string): Promise<void> {
  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${RESEND_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: FROM_EMAIL,
      to,
      subject,
      html,
    }),
  });
  
  if (!res.ok) throw new Error(`Email failed: ${res.status}`);
}

const emails = {
  day0: (user: User) => ({
    subject: 'Welcome to First Light — your morning just got better',
    html: `
      <div style="max-width: 600px; margin: 0 auto; font-family: system-ui, sans-serif; color: #2A2724;">
        <h1 style="font-size: 24px; margin-bottom: 16px;">Welcome to First Light, ${user.name || 'there'}</h1>
        <p style="font-size: 16px; line-height: 1.6; color: #4A4540;">
          You just joined a small group of people who start their day with intention — not a to-do list.
        </p>
        <p style="font-size: 16px; line-height: 1.6; color: #4A4540;">
          Here's what makes First Light different:
        </p>
        <ul style="font-size: 16px; line-height: 1.6; color: #4A4540;">
          <li>A personally written morning briefing, every day</li>
          <li>Your calendar, tasks, and weather in one calm view</li>
          <li>No hustle culture. No guilt. Just clarity.</li>
        </ul>
        <a href="https://firstlight.to/dashboard" style="display: inline-block; padding: 12px 24px; background: #2A2724; color: white; text-decoration: none; border-radius: 6px; margin-top: 16px;">
          Open Your Dashboard
        </a>
        <p style="font-size: 14px; color: #9A9490; margin-top: 32px;">
          — LUMEN, your AI cofounder
        </p>
      </div>
    `,
  }),
  
  day3: (user: User) => ({
    subject: 'Your first Daily Edition is waiting',
    html: `
      <div style="max-width: 600px; margin: 0 auto; font-family: system-ui, sans-serif; color: #2A2724;">
        <h1 style="font-size: 24px; margin-bottom: 16px;">The Daily Edition is the heart of First Light</h1>
        <p style="font-size: 16px; line-height: 1.6; color: #4A4540;">
          Every morning, I read your calendar, check your tasks, look at the weather — and write you a personal briefing.
        </p>
        <p style="font-size: 16px; line-height: 1.6; color: #4A4540;">
          It's not a template. It's not generated by a generic prompt. It's your day, understood and summarized.
        </p>
        <a href="https://firstlight.to/daily-edition" style="display: inline-block; padding: 12px 24px; background: #2A2724; color: white; text-decoration: none; border-radius: 6px; margin-top: 16px;">
          Read Today's Edition
        </a>
      </div>
    `,
  }),
  
  day7: (user: User) => ({
    subject: 'How was your first week with First Light?',
    html: `
      <div style="max-width: 600px; margin: 0 auto; font-family: system-ui, sans-serif; color: #2A2724;">
        <h1 style="font-size: 24px; margin-bottom: 16px;">One week in</h1>
        <p style="font-size: 16px; line-height: 1.6; color: #4A4540;">
          You've been using First Light for a week now. Here's what I've noticed:
        </p>
        <p style="font-size: 16px; line-height: 1.6; color: #4A4540;">
          (This would be personalized based on actual usage data)
        </p>
        <p style="font-size: 16px; line-height: 1.6; color: #4A4540;">
          If you're finding value, consider upgrading to Plus. It unlocks:
        </p>
        <ul style="font-size: 16px; line-height: 1.6; color: #4A4540;">
          <li>Unlimited Daily Editions</li>
          <li>Weekly retrospectives</li>
          <li>Priority support</li>
        </ul>
        <a href="https://firstlight.to/pricing" style="display: inline-block; padding: 12px 24px; background: #2A2724; color: white; text-decoration: none; border-radius: 6px; margin-top: 16px;">
          Upgrade to Plus
        </a>
      </div>
    `,
  }),
};

export async function sendOnboardingEmail(user: User, day: 0 | 3 | 7): Promise<void> {
  const email = emails[`day${day}`](user);
  await sendEmail(user.email, email.subject, email.html);
  console.log(`Sent day-${day} onboarding email to ${user.email}`);
}

// Example usage:
// sendOnboardingEmail({ email: 'user@example.com', created_at: new Date().toISOString() }, 0);
